//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class logAndPass
    {
        public int id { get; set; }
        public string logIn { get; set; }
        public string pass { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    }
}
